apiVersion: apps/v1
kind: Deployment

metadata:
  name: abc-technologies

spec:
  replicas: 2

  selector:
    matchLabels:
      app: abc-technologies

  template:
    metadata:
      labels:
        app: abc-technologies

    spec:
      containers:
      - name: abc-technologies
        image: abc-technologies:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80